// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcV9WUFaQ2Z9lRxTIm05r5WH7Nu_aBurM',
    appId: '1:807534588486:web:ecac04cfc8d638bb459047',
    messagingSenderId: '807534588486',
    projectId: 'cookit-1a276',
    authDomain: 'cookit-1a276.firebaseapp.com',
    storageBucket: 'cookit-1a276.appspot.com',
    measurementId: 'G-4JDR369V38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDekApZL1z4X8i5w7GhIZ0JMQS45sPmiaI',
    appId: '1:807534588486:android:9b0a102ce2d22ca3459047',
    messagingSenderId: '807534588486',
    projectId: 'cookit-1a276',
    storageBucket: 'cookit-1a276.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDpje-8vjgOd5_mvgSCG_FqRG9iZcG4v8',
    appId: '1:807534588486:ios:29fa585a0fdf674f459047',
    messagingSenderId: '807534588486',
    projectId: 'cookit-1a276',
    storageBucket: 'cookit-1a276.appspot.com',
    iosClientId: '807534588486-g51up57vag6vcu3j0kiuh35nft199b1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDpje-8vjgOd5_mvgSCG_FqRG9iZcG4v8',
    appId: '1:807534588486:ios:29fa585a0fdf674f459047',
    messagingSenderId: '807534588486',
    projectId: 'cookit-1a276',
    storageBucket: 'cookit-1a276.appspot.com',
    iosClientId: '807534588486-g51up57vag6vcu3j0kiuh35nft199b1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookit',
  );
}
