# Generated by Django 4.1.5 on 2023-03-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_delete_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
